enhance CLI_ISCONTAINED checks, reorder checks
git-svn: trunk@3586

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10404,78 +10404,6 @@ fi
 
 
 
-{ echo "$as_me:$LINENO: checking for gcc bug PR28045" >&5
-echo $ECHO_N "checking for gcc bug PR28045... $ECHO_C" >&6; }
-if test "$cross_compiling" = yes; then
-  { echo "$as_me:$LINENO: result: cross-compiling, assumed ok" >&5
-echo "${ECHO_T}cross-compiling, assumed ok" >&6; }
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* (C) Andrew Pinski */
-extern void abort(void);
-struct a
-{
-   unsigned int bits : 1;
-   signed long val : ((sizeof(long) * 8) - 1);
-};
-int Fnegate (struct a b)
-{
-  if ((-((long)b.val)) <= ((long) ((1UL << ((sizeof(long) * 8) - 2)) -1UL))
-      && (-((long)b.val)) >= (-(((long) ((1UL << ((sizeof(long) * 8) - 2)) -1UL))) - 1))
-     return 0 ;
-  abort ();
-}
-int main ()
-{
-  struct a b = {1, 1};
-  Fnegate (b);
-  return 0;
-}
-
-_ACEOF
-rm -f conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  { echo "$as_me:$LINENO: result: ok, bug not present" >&5
-echo "${ECHO_T}ok, bug not present" >&6; }
-else
-  echo "$as_me: program exited with status $ac_status" >&5
-echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-( exit $ac_status )
-{ { echo "$as_me:$LINENO: error: your compiler has gcc PR28045 bug, use a different compiler, see http://gcc.gnu.org/bugzilla/show_bug.cgi?id=28045" >&5
-echo "$as_me: error: your compiler has gcc PR28045 bug, use a different compiler, see http://gcc.gnu.org/bugzilla/show_bug.cgi?id=28045" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
-fi
-
-
-
 { echo "$as_me:$LINENO: checking for gcc bug PR26763-2" >&5
 echo $ECHO_N "checking for gcc bug PR26763-2... $ECHO_C" >&6; }
 if test "$cross_compiling" = yes; then
@@ -10561,13 +10489,13 @@ cat >>conftest.$ac_ext <<_ACEOF
 #include <stdio.h>
 static struct v{
 	char* dst;
-	unsigned long dsize;
-	unsigned long dcur;
-	unsigned long backsize;
- 	signed long unp_offset;
+	unsigned int dsize;
+	unsigned int dcur;
+	unsigned int backsize;
+	signed int unp_offset;
 } values[] = {
-	{(char*)0xf78ab008, 0x2e000, 1, 4, 0xfffff9f3},
-	{(char*)0xb7af1008, 0x2e000, 1, 4, 0xfffff9f3}
+	{(char*)0xf78ab008, 0x2e000, 1, 4, -1594},
+	{(char*)0xb7af1008, 0x2e000, 1, 4, -1594}
 
 };
 extern void abort(void);
@@ -10576,16 +10504,34 @@ extern void abort(void);
     (bb_size > 0 && sb_size > 0 && sb_size <= bb_size	\
      && sb >= bb && sb + sb_size <= bb + bb_size && sb + sb_size > bb)
 
+int crashtest()
+{
+	unsigned int backsize, dcur,i;
+	int dval=0x12000, unp_offset;
+	int* dsize = &dval;
+	char* dst = (char*)0x12000;
+	while(1) {
+		backsize=4;
+		dcur=0;
+		unp_offset=0x800002c7;
+
+		if (!CLI_ISCONTAINED(dst, *dsize, dst+dcur+unp_offset, backsize) || !CLI_ISCONTAINED(dst, *dsize, dst+dcur, backsize) || unp_offset >=0)
+			return -1;
+		abort();
+	}
+	return 0;
+}
+
 int main()
 {
 	int i;
 	for(i=0;i<sizeof(values)/sizeof(values[0]);i++) {
 		struct v* v= &values[i];
 		char* dst = v->dst;
-		unsigned long* dsize = &v->dsize;
-		unsigned long dcur = v->dcur;
-		unsigned long backsize = v->backsize-1;
-		signed long  unp_offset = v->unp_offset;
+		unsigned int* dsize = &v->dsize;
+		unsigned int dcur = v->dcur;
+		unsigned int backsize = v->backsize-1;
+		signed int  unp_offset = v->unp_offset;
 
 		if(!CLI_ISCONTAINED(dst, *dsize, dst+dcur+unp_offset, backsize) ||
 				!CLI_ISCONTAINED(dst, *dsize,dst+dcur,backsize) || unp_offset >= 0)  {
@@ -10593,6 +10539,7 @@ int main()
 		}
 		abort();
 	}
+	crashtest();
 	return 0;
 }
 
@@ -10625,12 +10572,85 @@ echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 ( exit $ac_status )
-{ { echo "$as_me:$LINENO: error: your compiler has a bug that causes clamav 670, use a different compiler, see http://bugs.clamav.net/bugzilla/show_bug.cgi?id=670" >&5
-echo "$as_me: error: your compiler has a bug that causes clamav 670, use a different compiler, see http://bugs.clamav.net/bugzilla/show_bug.cgi?id=670" >&2;}
+{ { echo "$as_me:$LINENO: error: your compiler has a bug that causes clamav bug no. 670, use a different compiler, see http://bugs.clamav.net/bugzilla/show_bug.cgi?id=670" >&5
+echo "$as_me: error: your compiler has a bug that causes clamav bug no. 670, use a different compiler, see http://bugs.clamav.net/bugzilla/show_bug.cgi?id=670" >&2;}
    { (exit 1); exit 1; }; }
 fi
 rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
+
+
+
+{ echo "$as_me:$LINENO: checking for gcc bug PR28045" >&5
+echo $ECHO_N "checking for gcc bug PR28045... $ECHO_C" >&6; }
+if test "$cross_compiling" = yes; then
+  { echo "$as_me:$LINENO: result: cross-compiling, assumed ok" >&5
+echo "${ECHO_T}cross-compiling, assumed ok" >&6; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* (C) Andrew Pinski */
+extern void abort(void);
+struct a
+{
+   unsigned int bits : 1;
+   signed long val : ((sizeof(long) * 8) - 1);
+};
+int Fnegate (struct a b)
+{
+  if ((-((long)b.val)) <= ((long) ((1UL << ((sizeof(long) * 8) - 2)) -1UL))
+      && (-((long)b.val)) >= (-(((long) ((1UL << ((sizeof(long) * 8) - 2)) -1UL))) - 1))
+     return 0 ;
+  abort ();
+}
+int main ()
+{
+  struct a b = {1, 1};
+  Fnegate (b);
+  return 0;
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  { echo "$as_me:$LINENO: result: ok, bug not present" >&5
+echo "${ECHO_T}ok, bug not present" >&6; }
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+{ { echo "$as_me:$LINENO: error: your compiler has gcc PR28045 bug, use a different compiler, see http://gcc.gnu.org/bugzilla/show_bug.cgi?id=28045" >&5
+echo "$as_me: error: your compiler has gcc PR28045 bug, use a different compiler, see http://gcc.gnu.org/bugzilla/show_bug.cgi?id=28045" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
 
 
 
