FPU endianess detection in configure
git-svn-id: file:///var/lib/svn/clamav-devel/branches/not_for_0.92_tempbranch@3316 77e5149b-7576-45b1-b177-96237e5ba77b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2750,7 +2750,7 @@ ac_config_headers="$ac_config_headers clamav-config.h"
 
 
 LC_CURRENT=3
-LC_REVISION=0
+LC_REVISION=1
 LC_AGE=0
 LIBCLAMAV_VERSION="$LC_CURRENT":"$LC_REVISION":"$LC_AGE"
 
@@ -26287,6 +26287,76 @@ _ACEOF
 fi
 { echo "$as_me:$LINENO: result: $have_signed_rightshift_extended" >&5
 echo "${ECHO_T}$have_signed_rightshift_extended" >&6; };
+
+{ echo "$as_me:$LINENO: checking whether FPU byte ordering is bigendian" >&5
+echo $ECHO_N "checking whether FPU byte ordering is bigendian... $ECHO_C" >&6; }
+if test "${ac_cv_c_fpu_bigendian+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_c_fpu_bigendian=unknown
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+double d = 3815911171354501045744583353695226502220105394563506259449467213186125718792664588210662403287568710818873279842508553551908601408568128557088985172985437412593385138085986771664896.0;
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+if grep emmeelle conftest.$ac_objext >/dev/null 2>&1 ; then
+	ac_cv_c_fpu_bigendian=yes
+fi
+if grep elleemme conftest.$ac_objext >/dev/null 2>&1 ; then
+	ac_cv_c_fpu_bigendian=no
+fi
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_c_fpu_bigendian" >&5
+echo "${ECHO_T}$ac_cv_c_fpu_bigendian" >&6; }
+case $ac_cv_c_fpu_bigendian in
+	yes)
+
+cat >>confdefs.h <<\_ACEOF
+#define FPU_WORDS_BIGENDIAN 1
+_ACEOF
+
+		;;
+	no)
+
+cat >>confdefs.h <<\_ACEOF
+#define FPU_WORDS_BIGENDIAN 0
+_ACEOF
+
+		;;
+	*)
+		{ echo "$as_me:$LINENO: WARNING: Unable to determine FPU endianess, some features may not be available in this build" >&5
+echo "$as_me: WARNING: Unable to determine FPU endianess, some features may not be available in this build" >&2;}
+esac
 
 
 ac_config_files="$ac_config_files libclamav/Makefile clamscan/Makefile database/Makefile docs/Makefile clamd/Makefile clamdscan/Makefile clamav-milter/Makefile freshclam/Makefile sigtool/Makefile clamconf/Makefile etc/Makefile Makefile clamav-config libclamav.pc docs/man/clamav-milter.8 docs/man/clamconf.1 docs/man/clamd.8 docs/man/clamd.conf.5 docs/man/clamdscan.1 docs/man/clamscan.1 docs/man/freshclam.1 docs/man/freshclam.conf.5 docs/man/sigtool.1"
