configure - check for sys/types.h
git-svn-id: file:///var/lib/svn/clamav-devel/trunk/clamav-devel@328 77e5149b-7576-45b1-b177-96237e5ba77b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10580,6 +10580,81 @@ _ACEOF
 
 fi
 
+# Check if <sys/select.h> needs to be included for fd_set
+echo "$as_me:$LINENO: checking for fd_set" >&5
+echo $ECHO_N "checking for fd_set... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <sys/types.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+fd_set readMask, writeMask;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_fd_set=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+have_fd_set=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+if test $have_fd_set = yes; then
+    echo "$as_me:$LINENO: result: yes, found in sys/types.h" >&5
+echo "${ECHO_T}yes, found in sys/types.h" >&6
+else
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <sys/select.h>
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  egrep "fd_mask" >/dev/null 2>&1; then
+  have_fd_set=yes
+fi
+rm -f conftest*
+
+    if test $have_fd_set = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SYS_SELECT_H 1
+_ACEOF
+
+        echo "$as_me:$LINENO: result: yes, found in sys/select.h" >&5
+echo "${ECHO_T}yes, found in sys/select.h" >&6
+    else
+
+cat >>confdefs.h <<\_ACEOF
+#define NO_FD_SET 1
+_ACEOF
+
+        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    fi
+fi
+
 ac_config_files="$ac_config_files libclamav/Makefile clamscan/Makefile database/Makefile docs/Makefile clamd/Makefile clamdscan/Makefile clamav-milter/Makefile freshclam/Makefile sigtool/Makefile etc/Makefile Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
