work around non reentrant lresolv
git-svn: trunk@4087

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15350,6 +15350,8 @@ _ACEOF
     fi
 fi
 
+
+
 # Check whether --enable-dns was given.
 if test "${enable_dns+set}" = set; then
   enableval=$enable_dns; want_dns=$enableval
@@ -15359,138 +15361,6 @@ else
 fi
 
 if test $want_dns = yes; then
-    { echo "$as_me:$LINENO: checking for __dn_expand in -lresolv" >&5
-echo $ECHO_N "checking for __dn_expand in -lresolv... $ECHO_C" >&6; }
-if test "${ac_cv_lib_resolv___dn_expand+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lresolv  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char __dn_expand ();
-int
-main ()
-{
-return __dn_expand ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_resolv___dn_expand=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_lib_resolv___dn_expand=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_resolv___dn_expand" >&5
-echo "${ECHO_T}$ac_cv_lib_resolv___dn_expand" >&6; }
-if test $ac_cv_lib_resolv___dn_expand = yes; then
-  resolv_lib="-lresolv"
-fi
-
-    if test -z "$resolv_lib"; then
-	{ echo "$as_me:$LINENO: checking for dn_expand in -lresolv" >&5
-echo $ECHO_N "checking for dn_expand in -lresolv... $ECHO_C" >&6; }
-if test "${ac_cv_lib_resolv_dn_expand+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lresolv  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char dn_expand ();
-int
-main ()
-{
-return dn_expand ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_resolv_dn_expand=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_lib_resolv_dn_expand=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_resolv_dn_expand" >&5
-echo "${ECHO_T}$ac_cv_lib_resolv_dn_expand" >&6; }
-if test $ac_cv_lib_resolv_dn_expand = yes; then
-  resolv_lib="-lresolv"
-fi
-
-    fi
     { echo "$as_me:$LINENO: checking for resolv.h" >&5
 echo $ECHO_N "checking for resolv.h... $ECHO_C" >&6; }
 if test "${ac_cv_header_resolv_h+set}" = set; then
@@ -15540,18 +15410,139 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_header_resolv_h" >&5
 echo "${ECHO_T}$ac_cv_header_resolv_h" >&6; }
 if test $ac_cv_header_resolv_h = yes; then
-  FRESHCLAM_LIBS="$FRESHCLAM_LIBS $resolv_lib"; CLAMAV_MILTER_LIBS="$CLAMAV_MILTER_LIBS $resolv_lib";
+
+	    bklibs=$LIBS;
+	    LIBS=-lresolv;
+	    { echo "$as_me:$LINENO: checking for dn_expand in -lresolv" >&5
+echo $ECHO_N "checking for dn_expand in -lresolv... $ECHO_C" >&6; }
+if test "${ac_cv_have_lresolv+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+	        ac_cv_have_lresolv=no;
+		cat >conftest.$ac_ext <<_ACEOF
+
+#include <sys/types.h>
+#include <netinet/in.h>
+#include <arpa/nameser.h>
+#include <resolv.h>
+int main() { return (int)dn_expand; }
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+		    ac_cv_have_lresolv=yes;
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_have_lresolv" >&5
+echo "${ECHO_T}$ac_cv_have_lresolv" >&6; }
+	    LIBS=$bklibs;
+
+fi
+
+
+    if test "x$ac_cv_have_lresolv" = "xyes"; then
+    	FRESHCLAM_LIBS="$FRESHCLAM_LIBS -lresolv";
+	CLAMAV_MILTER_LIBS="$CLAMAV_MILTER_LIBS -lresolv";
+	bklibs=$LIBS;
+	LIBS=-lresolv;
+
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_RESOLV_H 1
 _ACEOF
 
+	{ echo "$as_me:$LINENO: checking for res_nquery in -lresolv" >&5
+echo $ECHO_N "checking for res_nquery in -lresolv... $ECHO_C" >&6; }
+if test "${ac_cv_have_lresolv_r+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  { echo "$as_me:$LINENO: WARNING: ****** DNS support disabled" >&5
+
+	    ac_cv_have_lresolv_r=no;
+	    cat >conftest.$ac_ext <<_ACEOF
+
+#include <sys/types.h>
+#include <netinet/in.h>
+#include <arpa/nameser.h>
+#include <resolv.h>
+int main() { return (int)res_nquery; }
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+	        ac_cv_have_lresolv_r=yes;
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext,
+
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_have_lresolv_r" >&5
+echo "${ECHO_T}$ac_cv_have_lresolv_r" >&6; }
+	LIBS=$bklibs;
+	if test "x$ac_cv_have_lresolv_r" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LRESOLV_R 1
+_ACEOF
+
+	fi
+    else
+	{ echo "$as_me:$LINENO: WARNING: ****** DNS support disabled" >&5
 echo "$as_me: WARNING: ****** DNS support disabled" >&2;}
+    fi
 fi
 
 
-fi
 
 # Check whether --enable-clamuko was given.
 if test "${enable_clamuko+set}" = set; then
@@ -15802,6 +15793,10 @@ cat >>confdefs.h <<_ACEOF
 #define SENDMAIL_VERSION_C $sendmailver_c
 _ACEOF
 
+  fi
+  if test "x$ac_cv_have_lresolv_r" != "xyes"; then
+    { echo "$as_me:$LINENO: WARNING: ****** Your libresolv is not thread safe, SPF queries in clamav-milter will block" >&5
+echo "$as_me: WARNING: ****** Your libresolv is not thread safe, SPF queries in clamav-milter will block" >&2;}
   fi
 fi
 
