add testcase for gcc bug 37573, affecting gcc 4.1.2 at -O3 too (bb #1258)
git-svn: trunk@4302

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12556,6 +12556,130 @@ fi
 
 
 
+{ echo "$as_me:$LINENO: checking for gcc bug PR37573" >&5
+echo $ECHO_N "checking for gcc bug PR37573... $ECHO_C" >&6; }
+if test "$cross_compiling" = yes; then
+  { echo "$as_me:$LINENO: result: cross-compiling, assumed ok" >&5
+echo "${ECHO_T}cross-compiling, assumed ok" >&6; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+struct S
+{
+  unsigned int *a;
+  unsigned int b;
+  unsigned int c[624];
+};
+static unsigned char
+foo (struct S *s)
+{
+  unsigned int r;
+  if (!--s->b)
+    {
+      unsigned int *c = s->c;
+      unsigned int i;
+      s->a = c;
+      for (i = 0; i < 227; i++)
+	c[i] =
+	  ((((c[i] ^ c[i + 1]) & 0x7ffffffe) ^ c[i]) >> 1) ^
+	  ((0 - (c[i + 1] & 1)) & 0x9908b0df) ^ c[i + 397];
+      for (; i < 623; i++)
+	c[i] =
+	  ((((c[i] ^ c[i + 1]) & 0x7ffffffe) ^ c[i]) >> 1) ^
+	  ((0 - (c[i + 1] & 1)) & 0x9908b0df) ^ c[i - 227];
+      c[623] =
+	((((c[623] ^ c[0]) & 0x7ffffffe) ^ c[623]) >> 1) ^ ((0 - (c[0] & 1)) &
+							    0x9908b0df) ^ c[i
+									    -
+									    227];
+    }
+  r = *(s->a++);
+  r ^= (r >> 11);
+  r ^= ((r & 0xff3a58ad) << 7);
+  r ^= ((r & 0xffffdf8c) << 15);
+  r ^= (r >> 18);
+  return (unsigned char) (r >> 1);
+}
+
+void
+bar (unsigned char *p, unsigned int q, unsigned int r)
+{
+  struct S s;
+  unsigned int i;
+  unsigned int *c = s.c;
+  *c = r;
+  for (i = 1; i < 624; i++)
+    c[i] = i + 0x6c078965 * ((c[i - 1] >> 30) ^ c[i - 1]);
+  s.b = 1;
+  while (q--)
+    *p++ ^= foo (&s);
+};
+
+static unsigned char p[23] = {
+  0xc0, 0x49, 0x17, 0x32, 0x62, 0x1e, 0x2e, 0xd5, 0x4c, 0x19, 0x28, 0x49,
+    0x91, 0xe4, 0x72, 0x83, 0x91, 0x3d, 0x93, 0x83, 0xb3, 0x61, 0x38
+};
+
+static unsigned char q[23] = {
+  0x3e, 0x41, 0x55, 0x54, 0x4f, 0x49, 0x54, 0x20, 0x55, 0x4e, 0x49, 0x43,
+    0x4f, 0x44, 0x45, 0x20, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x3c
+};
+
+int
+main (void)
+{
+  unsigned int s;
+  s = 23;
+  bar (p, s, s + 0xa25e);
+  if (__builtin_memcmp (p, q, s) != 0)
+    __builtin_abort ();
+  return 0;
+}
+
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  { echo "$as_me:$LINENO: result: ok, bug not present" >&5
+echo "${ECHO_T}ok, bug not present" >&6; }
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+{ { echo "$as_me:$LINENO: error: your compiler has gcc PR37573 bug, use a different compiler, see http://gcc.gnu.org/bugzilla/show_bug.cgi?id=37573" >&5
+echo "$as_me: error: your compiler has gcc PR37573 bug, use a different compiler, see http://gcc.gnu.org/bugzilla/show_bug.cgi?id=37573" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+
 { echo "$as_me:$LINENO: checking for ld --version-script" >&5
 echo $ECHO_N "checking for ld --version-script... $ECHO_C" >&6; }
 if test "${ac_cv_ld_version_script+set}" = set; then
