fix make distcheck on gcc < 4.3  (bb #1259)
git-svn: trunk@4303

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -872,6 +872,8 @@ LIPO
 OTOOL
 OTOOL64
 CPP
+DISTCHECK_ENABLE_FLAGS_TRUE
+DISTCHECK_ENABLE_FLAGS_FALSE
 VERSIONSCRIPTFLAG
 VERSIONSCRIPT_TRUE
 VERSIONSCRIPT_FALSE
@@ -4753,13 +4755,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4756: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4758: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4759: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4761: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4762: output\"" >&5)
+  (eval echo "\"\$as_me:4764: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5970,7 +5972,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5973 "configure"' > conftest.$ac_ext
+  echo '#line 5975 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7821,11 +7823,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7824: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7826: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7828: \$? = $ac_status" >&5
+   echo "$as_me:7830: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8160,11 +8162,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8163: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8165: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8167: \$? = $ac_status" >&5
+   echo "$as_me:8169: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8265,11 +8267,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8268: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8270: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8272: \$? = $ac_status" >&5
+   echo "$as_me:8274: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8320,11 +8322,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8323: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8325: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8327: \$? = $ac_status" >&5
+   echo "$as_me:8329: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11076,7 +11078,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11079 "configure"
+#line 11081 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11172,7 +11174,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11175 "configure"
+#line 11177 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12236,6 +12238,27 @@ echo "${ECHO_T}ok (${gcc_version})" >&6; }
 else
 	CFLAGS="$CFLAGS -O0"
 	VERSION_SUFFIX="$VERSION_SUFFIX-broken-compiler"
+fi
+
+# add distcheck warning flags
+distcheck_enable_flags=0
+if test "x$ac_compiler_gnu" = "xyes"; then
+	gcc_version=`${CC} -dumpversion`
+	case "${gcc_version}" in
+		4.[3456789].*)
+			distcheck_enable_flags=1
+			;;
+		[56789].*)
+			distcheck_enable_flags=1
+			;;
+	esac
+fi
+ if test "x$distcheck_enable_flags" = "x1"; then
+  DISTCHECK_ENABLE_FLAGS_TRUE=
+  DISTCHECK_ENABLE_FLAGS_FALSE='#'
+else
+  DISTCHECK_ENABLE_FLAGS_TRUE='#'
+  DISTCHECK_ENABLE_FLAGS_FALSE=
 fi
 
 
@@ -21252,6 +21275,13 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${DISTCHECK_ENABLE_FLAGS_TRUE}" && test -z "${DISTCHECK_ENABLE_FLAGS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"DISTCHECK_ENABLE_FLAGS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"DISTCHECK_ENABLE_FLAGS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${VERSIONSCRIPT_TRUE}" && test -z "${VERSIONSCRIPT_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"VERSIONSCRIPT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -22265,6 +22295,8 @@ LIPO!$LIPO$ac_delim
 OTOOL!$OTOOL$ac_delim
 OTOOL64!$OTOOL64$ac_delim
 CPP!$CPP$ac_delim
+DISTCHECK_ENABLE_FLAGS_TRUE!$DISTCHECK_ENABLE_FLAGS_TRUE$ac_delim
+DISTCHECK_ENABLE_FLAGS_FALSE!$DISTCHECK_ENABLE_FLAGS_FALSE$ac_delim
 VERSIONSCRIPTFLAG!$VERSIONSCRIPTFLAG$ac_delim
 VERSIONSCRIPT_TRUE!$VERSIONSCRIPT_TRUE$ac_delim
 VERSIONSCRIPT_FALSE!$VERSIONSCRIPT_FALSE$ac_delim
@@ -22311,7 +22343,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 55; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 57; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
