initial support for hardware acceleration
git-svn: trunk@1895

diff --git a/clamav-devel/configure b/clamav-devel/configure
--- a/clamav-devel/configure
+++ b/clamav-devel/configure
@@ -10825,13 +10825,160 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_sn_sigscan_sn_sigscan_initdb" >&5
 echo "${ECHO_T}$ac_cv_lib_sn_sigscan_sn_sigscan_initdb" >&6
 if test $ac_cv_lib_sn_sigscan_sn_sigscan_initdb = yes; then
+  have_sigscan=yes
+fi
 
+    if test "$have_sigscan" = "yes"
+    then
+	if test "${ac_cv_header_sn_sigscan_sn_sigscan_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for sn_sigscan/sn_sigscan.h" >&5
+echo $ECHO_N "checking for sn_sigscan/sn_sigscan.h... $ECHO_C" >&6
+if test "${ac_cv_header_sn_sigscan_sn_sigscan_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_sn_sigscan_sn_sigscan_h" >&5
+echo "${ECHO_T}$ac_cv_header_sn_sigscan_sn_sigscan_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking sn_sigscan/sn_sigscan.h usability" >&5
+echo $ECHO_N "checking sn_sigscan/sn_sigscan.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <sn_sigscan/sn_sigscan.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking sn_sigscan/sn_sigscan.h presence" >&5
+echo $ECHO_N "checking sn_sigscan/sn_sigscan.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sn_sigscan/sn_sigscan.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: sn_sigscan/sn_sigscan.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: sn_sigscan/sn_sigscan.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sn_sigscan/sn_sigscan.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: sn_sigscan/sn_sigscan.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: sn_sigscan/sn_sigscan.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: sn_sigscan/sn_sigscan.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sn_sigscan/sn_sigscan.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: sn_sigscan/sn_sigscan.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sn_sigscan/sn_sigscan.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: sn_sigscan/sn_sigscan.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sn_sigscan/sn_sigscan.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: sn_sigscan/sn_sigscan.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sn_sigscan/sn_sigscan.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: sn_sigscan/sn_sigscan.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sn_sigscan/sn_sigscan.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: sn_sigscan/sn_sigscan.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for sn_sigscan/sn_sigscan.h" >&5
+echo $ECHO_N "checking for sn_sigscan/sn_sigscan.h... $ECHO_C" >&6
+if test "${ac_cv_header_sn_sigscan_sn_sigscan_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_sn_sigscan_sn_sigscan_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_sn_sigscan_sn_sigscan_h" >&5
+echo "${ECHO_T}$ac_cv_header_sn_sigscan_sn_sigscan_h" >&6
+
+fi
+if test $ac_cv_header_sn_sigscan_sn_sigscan_h = yes; then
+  LIBCLAMAV_LIBS="$LIBCLAMAV_LIBS -lsn_sigscan";
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_HWACCEL 1
 _ACEOF
 
+else
+  { echo "$as_me:$LINENO: WARNING: ****** hardware acceleration support disabled -- please install libsigscan-devel " >&5
+echo "$as_me: WARNING: ****** hardware acceleration support disabled -- please install libsigscan-devel " >&2;}
 fi
 
+
+    fi
 fi
 
 # Check whether --enable-dns or --disable-dns was given.
