Update
git-svn: trunk@102

diff --git a/clamav-devel/configure b/clamav-devel/configure
--- a/clamav-devel/configure
+++ b/clamav-devel/configure
@@ -8804,7 +8804,70 @@ if test $ac_cv_lib_gmp___gmpz_init = yes; then
 _ACEOF
 
 else
-  echo "WARNING: GNU MP 3 or newer NOT FOUND - digital signature support will be disabled !"; want_dsig="no"
+  echo "$as_me:$LINENO: checking for mpz_init in -lgmp" >&5
+echo $ECHO_N "checking for mpz_init in -lgmp... $ECHO_C" >&6
+if test "${ac_cv_lib_gmp_mpz_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgmp  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char mpz_init ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+mpz_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_gmp_mpz_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_gmp_mpz_init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_gmp_mpz_init" >&5
+echo "${ECHO_T}$ac_cv_lib_gmp_mpz_init" >&6
+if test $ac_cv_lib_gmp_mpz_init = yes; then
+  LIBCLAMAV_LIBS="$LIBCLAMAV_LIBS -lgmp"; cat >>confdefs.h <<\_ACEOF
+#define HAVE_GMP 1
+_ACEOF
+
+else
+  echo "WARNING: GNU MP 2 or newer NOT FOUND - digital signature support will be disabled !"; want_dsig="no"
+fi
+
 fi
 
 fi
@@ -8924,6 +8987,11 @@ fi
 if test "${enable_pthreads+set}" = set; then
   enableval="$enable_pthreads"
   have_pthreads=no
+else
+  cat >>confdefs.h <<\_ACEOF
+#define _REENTRANT 1
+_ACEOF
+
 fi;
 
 # Check whether --enable-cr or --disable-cr was given.
